name: Delete All Comments

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  delete-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete comments
        uses: peter-evans/delete-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
